// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"github.com/watchedsky-social/core/internal/database/models"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&models.Mapsearch{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&models.Mapsearch{}) fail: %s", err)
	}
}

func Test_mapsearchQuery(t *testing.T) {
	mapsearch := newMapsearch(_gen_test_db)
	mapsearch = *mapsearch.As(mapsearch.TableName())
	_do := mapsearch.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(mapsearch.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <mapsearch> fail:", err)
		return
	}

	_, ok := mapsearch.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from mapsearch success")
	}

	err = _do.Create(&models.Mapsearch{})
	if err != nil {
		t.Error("create item in table <mapsearch> fail:", err)
	}

	err = _do.Save(&models.Mapsearch{})
	if err != nil {
		t.Error("create item in table <mapsearch> fail:", err)
	}

	err = _do.CreateInBatches([]*models.Mapsearch{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <mapsearch> fail:", err)
	}

	_, err = _do.Select(mapsearch.ALL).Take()
	if err != nil {
		t.Error("Take() on table <mapsearch> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <mapsearch> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <mapsearch> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <mapsearch> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*models.Mapsearch{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <mapsearch> fail:", err)
	}

	_, err = _do.Select(mapsearch.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <mapsearch> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <mapsearch> fail:", err)
	}

	_, err = _do.Select(mapsearch.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <mapsearch> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <mapsearch> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <mapsearch> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <mapsearch> fail:", err)
	}

	_, err = _do.ScanByPage(&models.Mapsearch{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <mapsearch> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <mapsearch> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <mapsearch> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <mapsearch> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <mapsearch> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <mapsearch> fail:", err)
	}
}

var MapsearchPrefixSearchTestCase = []TestCase{}

func Test_mapsearch_PrefixSearch(t *testing.T) {
	mapsearch := newMapsearch(_gen_test_db)
	do := mapsearch.WithContext(context.Background()).Debug()

	for i, tt := range MapsearchPrefixSearchTestCase {
		t.Run("PrefixSearch_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.PrefixSearch(tt.Input.Args[0].(string))
			assert(t, "PrefixSearch", res1, tt.Expectation.Ret[0])
			assert(t, "PrefixSearch", res2, tt.Expectation.Ret[1])
		})
	}
}
