// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"github.com/watchedsky-social/core/internal/database/models"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&models.SavedArea{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&models.SavedArea{}) fail: %s", err)
	}
}

func Test_savedAreaQuery(t *testing.T) {
	savedArea := newSavedArea(_gen_test_db)
	savedArea = *savedArea.As(savedArea.TableName())
	_do := savedArea.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(savedArea.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <saved_areas> fail:", err)
		return
	}

	_, ok := savedArea.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from savedArea success")
	}

	err = _do.Create(&models.SavedArea{})
	if err != nil {
		t.Error("create item in table <saved_areas> fail:", err)
	}

	err = _do.Save(&models.SavedArea{})
	if err != nil {
		t.Error("create item in table <saved_areas> fail:", err)
	}

	err = _do.CreateInBatches([]*models.SavedArea{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <saved_areas> fail:", err)
	}

	_, err = _do.Select(savedArea.ALL).Take()
	if err != nil {
		t.Error("Take() on table <saved_areas> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <saved_areas> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <saved_areas> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <saved_areas> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*models.SavedArea{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <saved_areas> fail:", err)
	}

	_, err = _do.Select(savedArea.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <saved_areas> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <saved_areas> fail:", err)
	}

	_, err = _do.Select(savedArea.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <saved_areas> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <saved_areas> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <saved_areas> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <saved_areas> fail:", err)
	}

	_, err = _do.ScanByPage(&models.SavedArea{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <saved_areas> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <saved_areas> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <saved_areas> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <saved_areas> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <saved_areas> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <saved_areas> fail:", err)
	}
}

var SavedAreaInsertOptimizedSavedAreaTestCase = []TestCase{}

func Test_savedArea_InsertOptimizedSavedArea(t *testing.T) {
	savedArea := newSavedArea(_gen_test_db)
	do := savedArea.WithContext(context.Background()).Debug()

	for i, tt := range SavedAreaInsertOptimizedSavedAreaTestCase {
		t.Run("InsertOptimizedSavedArea_"+strconv.Itoa(i), func(t *testing.T) {
			res1 := do.InsertOptimizedSavedArea(tt.Input.Args[0].(string), tt.Input.Args[1].(string), tt.Input.Args[2].(string), tt.Input.Args[3].(*models.Geometry))
			assert(t, "InsertOptimizedSavedArea", res1, tt.Expectation.Ret[0])
		})
	}
}
