// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"github.com/watchedsky-social/core/internal/database/models"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&models.Zone{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&models.Zone{}) fail: %s", err)
	}
}

func Test_zoneQuery(t *testing.T) {
	zone := newZone(_gen_test_db)
	zone = *zone.As(zone.TableName())
	_do := zone.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(zone.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <zones> fail:", err)
		return
	}

	_, ok := zone.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from zone success")
	}

	err = _do.Create(&models.Zone{})
	if err != nil {
		t.Error("create item in table <zones> fail:", err)
	}

	err = _do.Save(&models.Zone{})
	if err != nil {
		t.Error("create item in table <zones> fail:", err)
	}

	err = _do.CreateInBatches([]*models.Zone{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <zones> fail:", err)
	}

	_, err = _do.Select(zone.ALL).Take()
	if err != nil {
		t.Error("Take() on table <zones> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <zones> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <zones> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <zones> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*models.Zone{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <zones> fail:", err)
	}

	_, err = _do.Select(zone.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <zones> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <zones> fail:", err)
	}

	_, err = _do.Select(zone.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <zones> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <zones> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <zones> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <zones> fail:", err)
	}

	_, err = _do.ScanByPage(&models.Zone{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <zones> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <zones> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <zones> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <zones> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <zones> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <zones> fail:", err)
	}
}

var ZoneCountVisibleZonesTestCase = []TestCase{}

func Test_zone_CountVisibleZones(t *testing.T) {
	zone := newZone(_gen_test_db)
	do := zone.WithContext(context.Background()).Debug()

	for i, tt := range ZoneCountVisibleZonesTestCase {
		t.Run("CountVisibleZones_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.CountVisibleZones(tt.Input.Args[0].(models.Geometry), tt.Input.Args[1].(models.Geometry))
			assert(t, "CountVisibleZones", res1, tt.Expectation.Ret[0])
			assert(t, "CountVisibleZones", res2, tt.Expectation.Ret[1])
		})
	}
}

var ZoneShowVisibleZonesTestCase = []TestCase{}

func Test_zone_ShowVisibleZones(t *testing.T) {
	zone := newZone(_gen_test_db)
	do := zone.WithContext(context.Background()).Debug()

	for i, tt := range ZoneShowVisibleZonesTestCase {
		t.Run("ShowVisibleZones_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.ShowVisibleZones(tt.Input.Args[0].(models.Geometry), tt.Input.Args[1].(models.Geometry))
			assert(t, "ShowVisibleZones", res1, tt.Expectation.Ret[0])
			assert(t, "ShowVisibleZones", res2, tt.Expectation.Ret[1])
		})
	}
}

var ZoneListIDsTestCase = []TestCase{}

func Test_zone_ListIDs(t *testing.T) {
	zone := newZone(_gen_test_db)
	do := zone.WithContext(context.Background()).Debug()

	for i, tt := range ZoneListIDsTestCase {
		t.Run("ListIDs_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.ListIDs()
			assert(t, "ListIDs", res1, tt.Expectation.Ret[0])
			assert(t, "ListIDs", res2, tt.Expectation.Ret[1])
		})
	}
}

var ZoneFindCongruentZonesTestCase = []TestCase{}

func Test_zone_FindCongruentZones(t *testing.T) {
	zone := newZone(_gen_test_db)
	do := zone.WithContext(context.Background()).Debug()

	for i, tt := range ZoneFindCongruentZonesTestCase {
		t.Run("FindCongruentZones_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindCongruentZones(tt.Input.Args[0].([]string))
			assert(t, "FindCongruentZones", res1, tt.Expectation.Ret[0])
			assert(t, "FindCongruentZones", res2, tt.Expectation.Ret[1])
		})
	}
}

var ZoneResolveGeometryTestCase = []TestCase{}

func Test_zone_ResolveGeometry(t *testing.T) {
	zone := newZone(_gen_test_db)
	do := zone.WithContext(context.Background()).Debug()

	for i, tt := range ZoneResolveGeometryTestCase {
		t.Run("ResolveGeometry_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.ResolveGeometry(tt.Input.Args[0].([]string))
			assert(t, "ResolveGeometry", res1, tt.Expectation.Ret[0])
			assert(t, "ResolveGeometry", res2, tt.Expectation.Ret[1])
		})
	}
}
