// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAlert = "alerts"

// Alert mapped from table <alerts>
type Alert struct {
	ID           string       `gorm:"column:id;primaryKey" json:"id,omitempty"`
	AreaDesc     string       `gorm:"column:area_desc;not null" json:"area_desc,omitempty"`
	Headline     string       `gorm:"column:headline;not null" json:"headline,omitempty"`
	Description  string       `gorm:"column:description;not null" json:"description,omitempty"`
	Severity     *string      `gorm:"column:severity" json:"severity,omitempty"`
	Certainty    *string      `gorm:"column:certainty" json:"certainty,omitempty"`
	Urgency      *string      `gorm:"column:urgency" json:"urgency,omitempty"`
	Event        *string      `gorm:"column:event" json:"event,omitempty"`
	Sent         time.Time    `gorm:"column:sent;not null" json:"sent,omitempty"`
	Effective    time.Time    `gorm:"column:effective;not null" json:"effective,omitempty"`
	Onset        *time.Time   `gorm:"column:onset" json:"onset,omitempty"`
	Expires      *time.Time   `gorm:"column:expires" json:"expires,omitempty"`
	Ends         *time.Time   `gorm:"column:ends" json:"ends,omitempty"`
	ReferenceIds *StringSlice `gorm:"column:reference_ids" json:"reference_ids,omitempty"`
	Border       *Geometry    `gorm:"column:border;not null;index:alert_border_geo_idx,priority:1" json:"border,omitempty"`
	MessageType  *string      `gorm:"column:message_type;not null;default:Alert" json:"message_type,omitempty"`
	SkeetInfo    *SkeetInfo   `gorm:"column:skeet_info" json:"skeet_info,omitempty"`
}

// TableName Alert's table name
func (*Alert) TableName() string {
	return TableNameAlert
}
