// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameDidwid = "didwids"

// Didwid mapped from table <didwids>
type Didwid struct {
	Did       string     `gorm:"column:did;primaryKey" json:"did"`
	Wid       string     `gorm:"column:wid;not null" json:"wid"`
	CreatedAt *time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName Didwid's table name
func (*Didwid) TableName() string {
	return TableNameDidwid
}
