// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameMapsearch = "mapsearch"

// Mapsearch mapped from table <mapsearch>
type Mapsearch struct {
	ID       string    `gorm:"column:id;primaryKey" json:"id,omitempty"`
	Name     string    `gorm:"column:name;not null" json:"name,omitempty"`
	State    string    `gorm:"column:state;not null" json:"state,omitempty"`
	County   *string   `gorm:"column:county" json:"county,omitempty"`
	Centroid *Geometry `gorm:"column:centroid;not null;index:mapsearch_centroid_idx,priority:1" json:"centroid,omitempty"`
}

// TableName Mapsearch's table name
func (*Mapsearch) TableName() string {
	return TableNameMapsearch
}
