// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameZone = "zones"

// Zone mapped from table <zones>
type Zone struct {
	ID     string    `gorm:"column:id;primaryKey" json:"id,omitempty"`
	Name   string    `gorm:"column:name;not null" json:"name,omitempty"`
	Type   string    `gorm:"column:type;not null" json:"type,omitempty"`
	State  *string   `gorm:"column:state;default:XX" json:"state,omitempty"`
	Border *Geometry `gorm:"column:border;not null;index:zone_border_geo_idx,priority:1" json:"border,omitempty"`
}

// TableName Zone's table name
func (*Zone) TableName() string {
	return TableNameZone
}
